#ifndef CAMERATYPE_H
#define CAMERATYPE_H

enum CAMERATYPE
{
    CAMERATYPE_LOCAL = 0,
    CAMERATYPE_WEB = 1,
};

enum CAMERASIZE
{
    CAMERASIZE_AUTO = 0,
    CAMERASIZE_1920x1080 = 1,
    CAMERASIZE_1280x720 = 2,
    CAMERASIZE_640x480 = 3,
};

#endif // CAMERATYPE_H
